name: Update JSON from Markdown




on:
  push:
    paths:
      - '**.md' # Markdown 파일이 변경될 때만 실행

jobs:
  update_json:
    name: Updat
    runs-on: ubuntu-latest

    steps:
      # - name: Run Python script
      #   run: python /djangomodelgallery/src/scripts/update_json.py
      - name: Print current directory
        run: find . -type f -name "update_json.py" 2>/dev/null